
pod:
 containerName: "container"
 imageName: ""
 containerPort: 80


services:
  name: "service"
  type: NodePort  #due to external IP pending issue, changed from LoadBalancer to NodePort
  devAppPort: 8086
  uatAppPort: 8087
  prodAppPort: 8088
  nodeDevPort: 30006
  nodeUatPort: 30016
  nodeProdPort: 30026

environment: ""

config:
  name: todo-app-config
  volume: todo-app-config-vol
  mountPath: config
